#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup

url = 'https://www.highlandparkwhisky.com/en-us'

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

print("Title is : ")
for title in soup.find_all('title'):
    print(title.get_text())
